# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: |
  (?x)^(
    (.*/)?\.vscode/.+|
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-yaml
        # exclude: |
        #   (?x)^(
        #     (.*/)?\.clang-format
        #   )$
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/igorshubovych/markdownlint-cli.git
    rev: v0.45.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/pylint-dev/pylint.git
    rev: v3.3.8
    hooks:
      - id: pylint # python 代码静态检测工具
        exclude: |
          (?x)^(
            BUILD
          )$
        language_version: python3
        args:
          - --rcfile=.pylintrc
          # 依赖 proto 生成的文件导致 github action 过不去, 暂时关了
          - --ignore-paths=^example/py/.*
        # 指定需要额外加载的依赖包或者模块
        additional_dependencies:
          - colorama
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black  # 著名的 Python 代码格式化工具
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort  # 自动排序和组织 import
        name: isort (python)
        # 解决 black 和 isort 相互冲突的问题
        # @see https://pycqa.github.io/isort/docs/configuration/black_compatibility.html
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff-check
        # args: [ --fix ] # 自动修复部分简单问题
      # ruff-format 会和 black formatter 冲突, 所以我们只开 ruff-check
      # - id: ruff-format
