name: Run all examples

on:
  push:
    branches: [ master dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    # example 依赖 cuda
    container: nvcr.io/nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install coverage coveralls ninja
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        apt update
        apt install -y google-perftools libgoogle-perftools-dev
        apt install -y thrift-compiler libthrift-dev
        apt install -y bison
        apt install -y flex
        apt install -y protobuf-compiler
        apt install -y libboost-all-dev
    - name: Run tests
      run: |
        bash scripts/example.sh
